In [3]:
import pandas as pd
#df.head(5)## accessing first five elements from .csv file
#df.tail(5)## Accessing last five element from .csv file

In [6]:
df=pd.read_csv('sales_report.csv')
df.head(5)

         Date     Product  Quantity  PricePerUnit  TotalPrice
0  2025-02-21      Tablet         3        490.54     1471.62
1  2025-03-13  Smartphone         4        986.89     3947.56
2  2025-02-26      Tablet         1        554.79      554.79
3  2025-01-08      Tablet        10        241.41     2414.05
4  2025-01-29  Headphones         1        805.20      805.20

In [7]:
df.tail(5)

          Date     Product  Quantity  PricePerUnit  TotalPrice
45  2025-05-07  Smartphone         1        878.48      878.48
46  2025-05-30      Laptop         8        516.95     4135.62
47  2025-03-09      Laptop         3        682.20     2046.60
48  2025-02-07  Smartphone         1        503.02      503.02
49  2025-04-23  Headphones         8        188.78     1510.20

In [8]:
df.describe()

        Quantity  PricePerUnit   TotalPrice
count  50.000000      50.00000    50.000000
mean    5.200000     537.24080  2708.897800
std     2.934663     271.91828  2236.773416
min     1.000000      78.60000    78.600000
25%     3.000000     309.71500   968.990000
50%     5.000000     509.98500  2020.460000
75%     8.000000     791.31500  3853.402500
max    10.000000     986.89000  9502.730000

In [9]:
df.dtypes

Date             object
Product          object
Quantity          int64
PricePerUnit    float64
TotalPrice      float64
dtype: object

In [10]:
##handling missing values
df.isnull()

     Date  Product  Quantity  PricePerUnit  TotalPrice
0   False    False     False         False       False
1   False    False     False         False       False
2   False    False     False         False       False
3   False    False     False         False       False
4   False    False     False         False       False
5   False    False     False         False       False
6   False    False     False         False       False
7   False    False     False         False       False
8   False    False     False         False       False
9   False    False     False         False       False
10  False    False     False         False       False
11  False    False     False         False       False
12  False    False     False         False       False
13  False    False     False         False       False
14  False    False     False         False       False
15  False    False     False         False       False
16  False    False     False         False       False
17  False    False     False         False       False
18  False    False     False         False       False
19  False    False     False         False       False
20  False    False     False         False       False
21  False    False     False         False       False
22  False    False     False         False       False
23  False    False     False         False       False
24  False    False     False         False       False
25  False    False     False         False       False
26  False    False     False         False       False
27  False    False     False         False       False
28  False    False     False         False       False
29  False    False     False         False       False
30  False    False     False         False       False
31  False    False     False         False       False
32  False    False     False         False       False
33  False    False     False         False       False
34  False    False     False         False       False
35  False    False     False         False       False
36  False    False     False         False       False
37  False    False     False         False       False
38  False    False     False         False       False
39  False    False     False         False       False
40  False    False     False         False       False
41  False    False     False         False       False
42  False    False     False         False       False
43  False    False     False         False       False
44  False    False     False         False       False
45  False    False     False         False       False
46  False    False     False         False       False
47  False    False     False         False       False
48  False    False     False         False       False
49  False    False     False         False       False

In [13]:
df.isnull().any()

Date            False
Product         False
Quantity        False
PricePerUnit    False
TotalPrice      False
dtype: bool

In [15]:
df.isnull().sum()

Date            0
Product         0
Quantity        0
PricePerUnit    0
TotalPrice      0
dtype: int64

In [17]:
df.dtypes

Date             object
Product          object
Quantity          int64
PricePerUnit    float64
TotalPrice      float64
dtype: object

In [20]:
##renaming columns
df=df.rename(columns={'Date':'Sales Date'})
df.head()

   Sales Date     Product  Quantity  PricePerUnit  TotalPrice
0  2025-02-21      Tablet         3        490.54     1471.62
1  2025-03-13  Smartphone         4        986.89     3947.56
2  2025-02-26      Tablet         1        554.79      554.79
3  2025-01-08      Tablet        10        241.41     2414.05
4  2025-01-29  Headphones         1        805.20      805.20

In [21]:
##change datatypes
df['Quantity_new']=df['Quantity'].astype(float)
df.head()

   Sales Date     Product  Quantity  PricePerUnit  TotalPrice  Quantity_new
0  2025-02-21      Tablet         3        490.54     1471.62           3.0
1  2025-03-13  Smartphone         4        986.89     3947.56           4.0
2  2025-02-26      Tablet         1        554.79      554.79           1.0
3  2025-01-08      Tablet        10        241.41     2414.05          10.0
4  2025-01-29  Headphones         1        805.20      805.20           1.0

In [22]:
##data aggregating and grouping
df.head()

   Sales Date     Product  Quantity  PricePerUnit  TotalPrice  Quantity_new
0  2025-02-21      Tablet         3        490.54     1471.62           3.0
1  2025-03-13  Smartphone         4        986.89     3947.56           4.0
2  2025-02-26      Tablet         1        554.79      554.79           1.0
3  2025-01-08      Tablet        10        241.41     2414.05          10.0
4  2025-01-29  Headphones         1        805.20      805.20           1.0

In [24]:
grouped_mean=df.groupby('Product')['PricePerUnit'].mean()
print(grouped_mean)

Product
Headphones    372.022222
Laptop        560.658000
Monitor       528.640000
Smartphone    657.312000
Tablet        548.031667
Name: PricePerUnit, dtype: float64

In [ ]:
df.groupby(['Product',''])

In [28]:
##merging and joining dataframes
df1=pd.DataFrame({'key':['A','B','C'], 'value1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','d'], 'value1':[4,5,6]})

In [26]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [29]:
df2

  key  value1
0   A       4
1   B       5
2   d       6

In [30]:
##merge dataframe on the 'key column'
pd.merge(df1,df2,on="key",how="inner")

  key  value1_x  value1_y
0   A         1         4
1   B         2         5

In [31]:
pd.merge(df1,df2,on="key",how="outer")

  key  value1_x  value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   d       NaN       6.0

In [32]:
pd.merge(df1,df2,on="key",how="left")

  key  value1_x  value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [33]:
pd.merge(df1,df2,on="key",how="right")

  key  value1_x  value1_y
0   A       1.0         4
1   B       2.0         5
2   d       NaN         6