Pandas:
1) Series : one dimensional array(array like object). it is similar to column in table
2) DataFrame : two dimensional array

In [2]:
import pandas as pd

In [4]:
import pandas as pd
data=[1,2,3,4,5]
series= pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
##cerate a series from dictionary
data={'a':1, 'b':2, 'c':3}
dc_series= pd.Series(data)
print(dc_series)

a    1
b    2
c    3
dtype: int64

In [7]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
##dataframe:two dimensional
##create a dataframe from a dictionary of list
data={
    'Name':['Shre','ya','chhaya'],
    'Age':[20,25,30],
    'City':['Ahmedabad','dwarka','goa']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0    Shre   20  Ahmedabad
1      ya   25     dwarka
2  chhaya   30        goa
<class 'pandas.core.frame.DataFrame'>

In [10]:
import numpy as np
np.array(df)

array([['Shre', 20, 'Ahmedabad'],
       ['ya', 25, 'dwarka'],
       ['chhaya', 30, 'goa']], dtype=object)

In [14]:
##create a dataframe from a list of dictionary
data=[
    {'name':'shr','age':30,'city':'banglore'},
    {'name':'ya_','age':30,'city':'banglore'},
]
df=pd.DataFrame(data)
print(df)

  name  age      city
0  shr   30  banglore
1  ya_   30  banglore

In [16]:
##accessing data from Dataframe
df

  name  age      city
0  shr   30  banglore
1  ya_   30  banglore

In [17]:
df['name']

0    shr
1    ya_
Name: name, dtype: object

In [ ]:
df.loc[0] ##first row index

C:\Users\shrey\AppData\Local\Temp\ipykernel_17056\1161040911.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0] ##first row index

'shr'

In [23]:
df.iloc[0][1]## index column

C:\Users\shrey\AppData\Local\Temp\ipykernel_17056\3032570200.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]## index column

np.int64(30)

In [ ]:
##accessing specified element
df.at[1,'age'] ##o/p: first index age value

np.int64(30)

In [29]:
##accessing specified element using iat
df.iat[1,2]

'banglore'

In [30]:
df

  name  age      city
0  shr   30  banglore
1  ya_   30  banglore

In [ ]:
##data manipulation with dataframe

##adding a column
df['salary']=[50000,60000]
df

  name  age      city  salary
0  shr   30  banglore   50000
1  ya_   30  banglore   60000

In [36]:
##remove a column: it is not permenant operation so we use inplace=true 
df.drop('salary',axis=1,inplace=True) ## bydefault axis value is 0, therefore it is checks only 1st row

In [37]:
df

  name  age      city
0  shr   30  banglore
1  ya_   30  banglore

In [40]:
##add age to column
df['age']=df['age']+1
df

  name  age      city
0  shr   33  banglore
1  ya_   33  banglore